### ISSUE TITLE
Heroku is no longer working

### ISSUE THREAD

**Issue by Fastmind-inc** [Bearer/Pizzly#210]
Heroku was workig perfectly then all of a sudden, with out redeploying I started getting 

> pizzly@0.2.0 db:migrate
> knex --cwd dist/src/lib/database/config migrate:latest

Using environment: production
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations

error: no pg_hba.conf entry for host "X.XX.XX.XX", user "XXXX", database "XXXXXXXXXXX", SSL off

    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by Fastmind-inc** [comment]
Problem Solved

Seems like the problem stand for adding a config var  PGSSLMODE = no-verify
The problem  comes from people who previously deployed an instance prior to that change. It has to be manually added.

**Comment by dflw-marcelo** [comment]
Thanks!

![Screen Shot 2021-03-17 at 11 58 47](https://user-images.githubusercontent.com/70495363/111488652-34384580-8718-11eb-961f-c661962eda3f.png)

**Comment by Fastmind-inc** [comment]
@dflw-marcelo You're welcome!

**Comment by cfabianski** [comment]
Thanks for the report. It's indeed linked to https://github.com/Bearer/Pizzly/issues/192

Happy you managed to have it fixed.
