### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by SteveSummerson** [Bearer/Pizzly#89]
Incredibly cool platform. I'm excited to test and when trying to install it locally or on an EC2 instance I'm not following where do you set the database credentials? 

On the getting started page, it goes right from `yarn install` to `yarn db:setup` it obviously failed since I would like to use a RDS hosted Postgres database and I never had the chance to update it. Does it go int he .envrc file? I did try that and then I get errors too of permission denied for 'ec2-user' 

Can you assist me with getting this installed? Any guidance where I can learn more about how to set all this up? 

I'm pretty new to Node, more of a PHP/Laravel (LAMP stack) dev

**Comment by Frenchcooc** [comment]
Hi Steve! I haven't tried installing Pizzly on EC2. But I believe it should work A to Z. What you need is to set environments variable to create the connection to the database.

If you look at the [database configuration file](https://github.com/Bearer/Pizzly/blob/master/src/lib/database/confi/index.ts), Pizzly uses `DATABASE_URL` which you can set with a PostgreSQL Connection URL (e.g. `postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]`).

If you don't know your connection URL on EC2, you can provide the host, port, user, password, etc. with the relevant variable. 

Hope that it helps. If you manage to make it work, let me know what was missing from the documentation and I will update it! Thanks

**Comment by Frenchcooc** [comment]
As said, I'm not familiar with EC2, but looks like JDBC URL are supported. Look at this tutorial: https://aws.amazon.com/getting-started/hands-on/create-connect-postgresql-db/

**Comment by Frenchcooc** [comment]
Hi @SteveSummerson! I'm closing this PR as I haven't  heard back from you. Feel free to comment again if you still need help

**Comment by SteveSummerson** [comment]
@Frenchcooc thanks so much for your response. 

I've actually decided to stick with the Heroku you've created as its the easiest way to get started. Still testing and learning more, I have quite a lot to learn. Seems investing time in learning node is a worthwhile investment so I've begun to do that. 

I did get the basics up and running and working fine. 

Again thanks for your response.

**Comment by eusonlito** [comment]
Hello @Frenchcooc!

I'm trying to install in a own VPS but .envrc is not used on `yarn db:setup`.

I have the `.envrc` file with:

```
###############################################################################
#
# Secure your instance
#
# 1. Secure access to the dashboard
#
export DASHBOARD_USERNAME="XXXXXXXXXXXXXXXXXX"
export DASHBOARD_PASSWORD="XXXXXXXXXXXXXXXXXX"
#
# 2. Secure requests to the API
#
export SECRET_KEY="XXXXXXXXXXXXXXXXXX"
export PUBLISHABLE_KEY="XXXXXXXXXXXXXXXXXX"
#
# 3. Allow or disable requests to the proxy service using a publishable key.
#    FALSE by default to allow request with a publishable key or a secret key.
#    Set to TRUE to only allow access having a valid secret key.
#
export PROXY_USES_SECRET_KEY_ONLY=false
#
# 4. Replace the default cookie secret to an unguessable string
#    Learn more: https://github.com/expressjs/cookie-session
#
export COOKIE_SECRET="XXXXXXXXXXXXXXXXXX"
#
###############################################################################
#
# Database connection
#
# 1. Use a connection URI
#
# export DATABASE_URL=""
#
# 2. Provide specific database attributes
#
export DB_USER="pizzly"
export DB_PASSWORD="pizzly"
export DB_HOST="localhost"
export DB_PORT="5432"
export DB_DATABASE="pizzly"
#
#
###############################################################################
# 
# Other options
#
# - Uncomment to set the callback URL used for the OAuth dance.
#   Otherwise, Pizzly will use the req.hostname.
#
# export AUTH_CALLBACK_URL="http://example.org/auth/callback"
#
# - Uncomment to enable Bearer.sh to monitor and shield your Pizzly instance.
#   To get your BEARER_SECRET_KEY, create an account on www.bearer.sh
#   then heads to https://app.bearer.sh/settings/key
#
# export BEARER_SECRET_KEY=""
```
But yarn command return:

```
$ yarn db:setup
yarn run v1.22.5

$ npm run db:create && npm run db:migrate
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599567698774-0.9465012655370144/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> pizzly@0.2.0 db:create /var/www/pizzly/www
> node dist/src/lib/database/config/create

(node:1737359) UnhandledPromiseRejectionWarning: error: password authentication failed for user "www-data"
    at Parser.parseErrorMessage (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/pizzly/www/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:1737359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1737359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599567698774-0.9465012655370144/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> pizzly@0.2.0 db:migrate /var/www/pizzly/www
> knex --cwd dist/src/lib/database/config migrate:latest

Using environment: development
error: password authentication failed for user "www-data"
    at Parser.parseErrorMessage (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/pizzly/www/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/pizzly/www/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pizzly@0.2.0 db:migrate: `knex --cwd dist/src/lib/database/config migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pizzly@0.2.0 db:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/www-data/.npm/_logs/2020-09-08T12_21_40_055Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks!

**Comment by eusonlito** [comment]
Finally I was able to run db:setup with a previous environment init with: `. .envrc`:

```
$ . .envrc

$ yarn db:setup
yarn run v1.22.5
$ npm run db:create && npm run db:migrate
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599583576583-0.9079229636409265/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> pizzly@0.2.0 db:create /var/www/pizzly/www
> node dist/src/lib/database/config/create

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1599583576583-0.9079229636409265/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> pizzly@0.2.0 db:migrate /var/www/pizzly/www
> knex --cwd dist/src/lib/database/config migrate:latest

Using environment: development
Batch 1 run: 8 migrations
Done in 1.43s.
```

**Comment by Frenchcooc** [comment]
@eusonlito just reading your comment right now. I'm sorry for that. I'd rather recommend you to create new issues next time. I'm not notified on closed issues. Great that you managed to make it work by yourself!

**Comment by eusonlito** [comment]
@Frenchcooc no problem! I preferred not to repeat issues (about installation problems) :)
